
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package systemutvecklingsprojekt;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.nio.charset.Charset;
import java.nio.file.Files;
import java.sql.Connection;
import java.security.NoSuchAlgorithmException;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.BoxLayout;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.Random;

/**
 *
 * @author vince
 */
public class Inloggad extends javax.swing.JFrame {

    private static Connection db;
    private int anvandarID;
    private String adminStatus;
    private String filNamn;
    private File fil;
    private String filePath;
    private String dagensDatum;
    private DefaultComboBoxModel cmbProjektModel;

    /**
     * Creates new form Inloggad
     */
    public Inloggad(Connection db, int anvandarID, String adminStatus) {

        this.db = db;
        this.anvandarID = anvandarID;
        this.adminStatus = adminStatus;
        initComponents();
        this.filNamn = "";
        cmbProjektModel = new DefaultComboBoxModel();

        pnlFormellBlogg.setLayout(new BoxLayout(pnlFormellBlogg, BoxLayout.Y_AXIS));
        pnlInformellBlogg.setLayout(new BoxLayout(pnlInformellBlogg, BoxLayout.Y_AXIS));
        pnlProjektInlagg.setLayout(new BoxLayout(pnlProjektInlagg, BoxLayout.Y_AXIS));

        if (adminStatus.equals("N")) {
            tabbedPaneBar.remove(1);
        }

        try {
            uppdateraInformellBlogg();
            uppdateraFormellBlogg();
            fyllPåCmbProjektgrupper();
        } catch (SQLException e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton9 = new javax.swing.JButton();
        jTextField11 = new javax.swing.JTextField();
        jFrame1 = new javax.swing.JFrame();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jSeparator1 = new javax.swing.JSeparator();
        tabbedPaneBar = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        ScrollPane1 = new javax.swing.JScrollPane();
        pnlInformellBlogg = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        btnUppdateraInformell = new javax.swing.JButton();
        btnSorteraLikes = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        ScrollPane3 = new javax.swing.JScrollPane();
        pnlFormellBlogg = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        btnUppdateraFormell = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        txtSattRubrik = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btnLaggTillFil = new javax.swing.JButton();
        lblVisaFilnamn = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        cmbInlaggsTyp = new javax.swing.JComboBox<>();
        btnPublicera = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtBrodtext = new javax.swing.JTextArea();
        lblValjBlogg = new javax.swing.JLabel();
        pnlAdminRights = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        txtEpost = new javax.swing.JTextField();
        txtTelefonnummer = new javax.swing.JTextField();
        txtFornamn = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btnSkapaKonto = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        txtEfternamn = new javax.swing.JTextField();
        rbtnAdmin = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnNyttProjektInlagg = new javax.swing.JButton();
        cmbProjektLista = new javax.swing.JComboBox<>();
        lblValjProjektgrupp = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnSkapaNyProjektgrupp = new javax.swing.JButton();
        scrlProjektGrupper = new javax.swing.JScrollPane();
        pnlProjektInlagg = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnUppdateraProjekt = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnSkapaNyttMote = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtVisaResultat = new javax.swing.JTextArea();
        btnVisaResultat = new javax.swing.JButton();
        jCal = new com.toedter.calendar.JCalendar();
        btnMinaMoten = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jButton9.setText("jButton9");

        jTextField11.setText("jTextField11");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        tabbedPaneBar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTabbedPane2.setRequestFocusEnabled(false);

        javax.swing.GroupLayout pnlInformellBloggLayout = new javax.swing.GroupLayout(pnlInformellBlogg);
        pnlInformellBlogg.setLayout(pnlInformellBloggLayout);
        pnlInformellBloggLayout.setHorizontalGroup(
            pnlInformellBloggLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 912, Short.MAX_VALUE)
        );
        pnlInformellBloggLayout.setVerticalGroup(
            pnlInformellBloggLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2333, Short.MAX_VALUE)
        );

        ScrollPane1.setViewportView(pnlInformellBlogg);

        jLabel19.setIcon(new javax.swing.ImageIcon("C:\\Users\\ifkli\\OneDrive\\Skrivbord\\InFormellaBloggenMild.png")); // NOI18N

        btnUppdateraInformell.setText("Uppdatera");
        btnUppdateraInformell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUppdateraInformellActionPerformed(evt);
            }
        });

        btnSorteraLikes.setText("Sortera efter likes");
        btnSorteraLikes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSorteraLikesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUppdateraInformell)
                    .addComponent(btnSorteraLikes))
                .addGap(34, 34, 34)
                .addComponent(ScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel19)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(btnUppdateraInformell)
                        .addGap(26, 26, 26)
                        .addComponent(btnSorteraLikes)
                        .addContainerGap(498, Short.MAX_VALUE))))
        );

        jTabbedPane2.addTab("Informell", jPanel7);

        javax.swing.GroupLayout pnlFormellBloggLayout = new javax.swing.GroupLayout(pnlFormellBlogg);
        pnlFormellBlogg.setLayout(pnlFormellBloggLayout);
        pnlFormellBloggLayout.setHorizontalGroup(
            pnlFormellBloggLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 912, Short.MAX_VALUE)
        );
        pnlFormellBloggLayout.setVerticalGroup(
            pnlFormellBloggLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2333, Short.MAX_VALUE)
        );

        ScrollPane3.setViewportView(pnlFormellBlogg);

        jLabel28.setIcon(new javax.swing.ImageIcon("C:\\Users\\ifkli\\OneDrive\\Skrivbord\\FormellaBloggenMild.png")); // NOI18N

        btnUppdateraFormell.setText("Uppdatera");
        btnUppdateraFormell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUppdateraFormellActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnUppdateraFormell)
                .addGap(43, 43, 43)
                .addComponent(ScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 1016, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel28)
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnUppdateraFormell)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Formell", jPanel10);

        txtSattRubrik.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel7.setText("Rubrik");

        jLabel18.setText("Brödtext");

        btnLaggTillFil.setText("Lägg till fil");
        btnLaggTillFil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaggTillFilActionPerformed(evt);
            }
        });

        lblVisaFilnamn.setText("Filnamn");

        jLabel26.setText("#");

        cmbInlaggsTyp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Informell blogg", "Formell blogg" }));

        btnPublicera.setText("Publicera");
        btnPublicera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPubliceraActionPerformed(evt);
            }
        });

        jLabel31.setIcon(new javax.swing.ImageIcon("C:\\Users\\ifkli\\OneDrive\\Skrivbord\\SkapaNyttInlaggMild.png")); // NOI18N

        txtBrodtext.setColumns(20);
        txtBrodtext.setLineWrap(true);
        txtBrodtext.setRows(5);
        jScrollPane1.setViewportView(txtBrodtext);

        lblValjBlogg.setText("Välj blogg");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtSattRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnPublicera)
                            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbInlaggsTyp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnLaggTillFil)
                                    .addComponent(lblVisaFilnamn, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(211, 211, 211)
                                .addComponent(jLabel26))
                            .addComponent(lblValjBlogg, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jLabel31)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSattRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblValjBlogg)
                        .addGap(18, 18, 18)
                        .addComponent(cmbInlaggsTyp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel26)
                        .addGap(42, 42, 42)
                        .addComponent(btnLaggTillFil)
                        .addGap(18, 18, 18)
                        .addComponent(lblVisaFilnamn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(btnPublicera)
                .addContainerGap(201, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 1066, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Skapa nytt inlägg", jPanel8);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1021, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        tabbedPaneBar.addTab("Blogg", jPanel1);

        jLabel12.setText("E-post (inlogg)");

        jLabel15.setText("Telefonnummer");

        jLabel16.setText("Förnamn");

        btnSkapaKonto.setText("Skapa nytt användarkonto");
        btnSkapaKonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSkapaKontoActionPerformed(evt);
            }
        });

        jLabel17.setText("Efternamn");

        rbtnAdmin.setText("Administratör");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Skapa konto");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtEpost, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTelefonnummer)
                            .addComponent(rbtnAdmin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                        .addGap(55, 55, 55)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnSkapaKonto)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtEfternamn)
                                    .addComponent(txtFornamn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(29, 29, 29))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFornamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefonnummer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnAdmin)
                    .addComponent(btnSkapaKonto))
                .addGap(58, 58, 58))
        );

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\ifkli\\OneDrive\\Skrivbord\\AdministratorBannerTest.png")); // NOI18N

        javax.swing.GroupLayout pnlAdminRightsLayout = new javax.swing.GroupLayout(pnlAdminRights);
        pnlAdminRights.setLayout(pnlAdminRightsLayout);
        pnlAdminRightsLayout.setHorizontalGroup(
            pnlAdminRightsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdminRightsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5))
            .addGroup(pnlAdminRightsLayout.createSequentialGroup()
                .addGap(257, 257, 257)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlAdminRightsLayout.setVerticalGroup(
            pnlAdminRightsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminRightsLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(305, Short.MAX_VALUE))
        );

        tabbedPaneBar.addTab("Admin", pnlAdminRights);

        btnNyttProjektInlagg.setText("Nytt inlägg");
        btnNyttProjektInlagg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNyttProjektInlaggActionPerformed(evt);
            }
        });

        cmbProjektLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProjektListaActionPerformed(evt);
            }
        });

        lblValjProjektgrupp.setText("Välj projektgrupp:");

        btnSkapaNyProjektgrupp.setText("Skapa Ny Projektgrupp");
        btnSkapaNyProjektgrupp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSkapaNyProjektgruppActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlProjektInlaggLayout = new javax.swing.GroupLayout(pnlProjektInlagg);
        pnlProjektInlagg.setLayout(pnlProjektInlaggLayout);
        pnlProjektInlaggLayout.setHorizontalGroup(
            pnlProjektInlaggLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 697, Short.MAX_VALUE)
        );
        pnlProjektInlaggLayout.setVerticalGroup(
            pnlProjektInlaggLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 637, Short.MAX_VALUE)
        );

        scrlProjektGrupper.setViewportView(pnlProjektInlagg);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/systemutvecklingsprojekt/ProjektGrupperMild.png"))); // NOI18N

        btnUppdateraProjekt.setText("Uppdatera");
        btnUppdateraProjekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUppdateraProjektActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1021, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(scrlProjektGrupper, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblValjProjektgrupp)
                    .addComponent(btnNyttProjektInlagg)
                    .addComponent(cmbProjektLista, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSkapaNyProjektgrupp)
                    .addComponent(btnUppdateraProjekt))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel1))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrlProjektGrupper, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblValjProjektgrupp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbProjektLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNyttProjektInlagg)
                        .addGap(92, 92, 92)
                        .addComponent(btnUppdateraProjekt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSkapaNyProjektgrupp)
                        .addGap(14, 14, 14))))
        );

        tabbedPaneBar.addTab("Projekt", jPanel2);

        btnSkapaNyttMote.setText("Skapa nytt möte");
        btnSkapaNyttMote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSkapaNyttMoteActionPerformed(evt);
            }
        });

        txtVisaResultat.setEditable(false);
        txtVisaResultat.setColumns(20);
        txtVisaResultat.setLineWrap(true);
        txtVisaResultat.setRows(5);
        jScrollPane2.setViewportView(txtVisaResultat);

        btnVisaResultat.setText("Visa publika möten");
        btnVisaResultat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisaResultatActionPerformed(evt);
            }
        });

        jCal.setDate(new java.util.Date(1587630375000L));
        jCal.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jCalPropertyChange(evt);
            }
        });

        btnMinaMoten.setText("Visa mina möten");
        btnMinaMoten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinaMotenActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Mötesinbjudningar");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCal, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnVisaResultat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMinaMoten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnSkapaNyttMote)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(42, 42, 42))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSkapaNyttMote)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jCal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVisaResultat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMinaMoten))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(282, Short.MAX_VALUE))
        );

        tabbedPaneBar.addTab("Kalender", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPaneBar, javax.swing.GroupLayout.PREFERRED_SIZE, 1022, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPaneBar)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSkapaNyProjektgruppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkapaNyProjektgruppActionPerformed
        new SkapaNyttProjekt(db, anvandarID).setVisible(true);
    }//GEN-LAST:event_btnSkapaNyProjektgruppActionPerformed

    private void cmbProjektListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProjektListaActionPerformed
        //scrlProjektGrupper .add();
        
        if(!(cmbProjektLista.getItemCount() == 0)){

        pnlProjektInlagg.removeAll();

        validate();
        if (!cmbProjektLista.getSelectedItem().toString().equals("Forskning:") || !cmbProjektLista.getSelectedItem().toString().equals("Utbildning:") || !cmbProjektLista.getSelectedItem().toString().equals("Inga Projekt")) {
            try {
                ArrayList<ArrayList<String>> projektInlagg = SQL.lasInProjektGrupper(db, cmbProjektLista.getSelectedItem().toString());
                ArrayList<ProjektInlaggsPanel> inlaggPaneler = new ArrayList<>();

                for (ArrayList<String> inlagg : projektInlagg) {
                    String projektInlaggID = inlagg.get(0);
                    String rubrik = inlagg.get(1);
                    String text = inlagg.get(2);
                    String filURL = inlagg.get(3);
                    String skapatAvID = inlagg.get(4);
                    String namn = inlagg.get(6);
                    ProjektInlaggsPanel nyttProjektInlagg = new ProjektInlaggsPanel(db, rubrik, text, skapatAvID, filURL, anvandarID, namn, projektInlaggID);
                    inlaggPaneler.add(nyttProjektInlagg);
                }

                for (ProjektInlaggsPanel inlagg : inlaggPaneler) {
                    pnlProjektInlagg.add(inlagg);
                }
                revalidate();
            } catch (SQLException e) {

            }

        }
        revalidate();
        }
    }//GEN-LAST:event_cmbProjektListaActionPerformed

    private void btnNyttProjektInlaggActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNyttProjektInlaggActionPerformed
        if (!cmbProjektLista.getSelectedItem().toString().equals("Forskning:") && !cmbProjektLista.getSelectedItem().toString().equals("Utbildning:") && !cmbProjektLista.getSelectedItem().toString().equals("Inga Projekt")) {
            try {
                String rubrik = "";
                String text = "";
                String filURL = "";
                String skrivenAv = Integer.toString(anvandarID);
                String projektInlaggID = Integer.toString(1);
                int projektGruppID = SQL.hamtaProjektGruppID(db, cmbProjektLista.getSelectedItem().toString());
                ProjektInlagg projektInlagg = new ProjektInlagg(db, rubrik, text, skrivenAv, filURL, anvandarID, projektInlaggID, projektGruppID);
                projektInlagg.setVisible(true);

            } catch (SQLException e) {

            }
        } else {
            JOptionPane.showMessageDialog(null, "Var vänlig välj en projektgrupp i rullistan.");
        }

    }//GEN-LAST:event_btnNyttProjektInlaggActionPerformed

    private void btnSkapaKontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkapaKontoActionPerformed

        String epost = txtEpost.getText();
        String fornamn = txtFornamn.getText();
        String efternamn = txtEfternamn.getText();
        String losenord = genereratLosenord();
        String telefonNummer = txtTelefonnummer.getText();
        String admin = "";

        if (rbtnAdmin.isSelected()) {
            admin = "J";
        } else {
            admin = "N";
        }

        if (Validering.textIsEmpty(txtEpost)) {
            JOptionPane.showMessageDialog(null, "Vänligen fyll i en E-post");
        } else if (Validering.textIsEmpty(txtFornamn)) {
            JOptionPane.showMessageDialog(null, "Vänligen fyll i förnamn");
        } else if (Validering.textIsEmpty(txtEfternamn)) {
            JOptionPane.showMessageDialog(null, "Vänligen fyll i efternamn");
        } else if (Validering.textIsEmpty(txtTelefonnummer) || Validering.checkPhoneLength(txtTelefonnummer)) {
            JOptionPane.showMessageDialog(null, "Telefonnummer måste vara mellan 1-30 siffror");
        } else {
            try {
                SQL.laggTillAnvandare(db, epost, fornamn, efternamn, losenord, telefonNummer, admin);
                JOptionPane.showMessageDialog(null, "Kontot har skapats!" + System.lineSeparator() + "Ditt lösenord är: "
                        + losenord + System.lineSeparator() + "Du kan ändra lösenordet när du loggar in.");
                tomFalt();
            } catch (NoSuchAlgorithmException i) {

            } catch (SQLException e) {

            }
        }
    }//GEN-LAST:event_btnSkapaKontoActionPerformed

    private String genereratLosenord() {

        // lower limit for LowerCase Letters 
        int lowerLimit = 97;

        // lower limit for LowerCase Letters 
        int upperLimit = 122;

        Random random = new Random();

        // Create a StringBuffer to store the result 
        StringBuffer r = new StringBuffer(6);

        for (int i = 0; i < 6; i++) {

            // take a random value between 97 and 122 
            int nextRandomChar = lowerLimit
                    + (int) (random.nextFloat()
                    * (upperLimit - lowerLimit + 1));

            // append a character at the end of bs 
            r.append((char) nextRandomChar);
        }

        // return the resultant string 
        return r.toString();
    }


    private void btnPubliceraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPubliceraActionPerformed

        try {
            if (Validering.textIsEmpty(txtSattRubrik)) {
                JOptionPane.showMessageDialog(null, "Vänligen fyll i rubrik");
            } else if (Validering.textAreaIsEmpty(txtBrodtext)) {
                JOptionPane.showMessageDialog(null, "Vänligen fyll i brödtext");
            } else if (cmbInlaggsTyp.getSelectedItem().toString().equals("Informell blogg") && filNamn.contains(".pdf")) {
                JOptionPane.showMessageDialog(null, "Du måste välja en jpg eller en png");
            } else {
                if (filNamn.equals("")) {
                    filePath = "";
                } else {
                    sparaFil(fil, filNamn);
                }
                SQL.laggaTillBloggInlagg(db, txtSattRubrik.getText(), txtBrodtext.getText(), filePath, anvandarID, cmbInlaggsTyp.getSelectedItem().toString());
                tomFalt();
                JOptionPane.showMessageDialog(null, "Inlägg publicerat!");
            }
        } catch (NoSuchAlgorithmException e) {
        } catch (SQLException e) {
        }
    }//GEN-LAST:event_btnPubliceraActionPerformed

    private void btnLaggTillFilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaggTillFilActionPerformed

        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        fil = chooser.getSelectedFile();

        String filName = String.valueOf(fil);

        if (!filName.equals("null")) {
            filNamn = chooser.getName(fil);
            if (cmbInlaggsTyp.getSelectedItem().equals("Formell blogg")) {

                if (checkPdf(filNamn) || checkPng(filNamn) || checkJpg(filNamn)) {
                    int input = JOptionPane.showConfirmDialog(null, "Filen kommer försvinna från din dator. "
                            + "Om du vill spara filen på datorn, skapa en kopia innan du publicerar.", null,
                            JOptionPane.OK_CANCEL_OPTION);

                    if (input == 0) {
                        lblVisaFilnamn.setText(filNamn);

                    } else if (input == 2) {
                        lblVisaFilnamn.setText("Filnamn");

                        filNamn = "";

                    }

                } else {

                    JOptionPane.showMessageDialog(null, "Du måste välja en pdf, jpg eller en png");
                }
            } else {
                if (checkPng(filNamn) || checkJpg(filNamn)) {
                    int input = JOptionPane.showConfirmDialog(null, "Filen kommer försvinna från din dator. "
                            + "Om du vill spara filen på datorn, skapa en kopia innan du publicerar.", null,
                            JOptionPane.OK_CANCEL_OPTION);

                    if (input == 0) {
                        lblVisaFilnamn.setText(filNamn);

                    } else if (input == 2) {
                        lblVisaFilnamn.setText("Filnamn");

                        filNamn = "";

                    }

                } else {
                    JOptionPane.showMessageDialog(null, "Du måste välja en jpg eller en png");
                }

            }
        }
    }//GEN-LAST:event_btnLaggTillFilActionPerformed

    private void btnSorteraLikesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSorteraLikesActionPerformed

        try {

            pnlInformellBlogg.removeAll();

            ArrayList<ArrayList<String>> bloggInlagg = SQL.sorteraEfterLikes(db);
            ArrayList<BloggInlaggsPanel> inlaggPaneler = new ArrayList<>();

            for (ArrayList<String> inlagg : bloggInlagg) {
                String rubrik = inlagg.get(0);
                String text = inlagg.get(1);
                String filURL = inlagg.get(2);
                String datum = inlagg.get(3);
                String skapatAv = inlagg.get(4);
                String bloggInlaggID = inlagg.get(5);
                String namn = inlagg.get(6);
                BloggInlaggsPanel nyttInlagg = new BloggInlaggsPanel(db, rubrik, text, skapatAv, datum, filURL, anvandarID, bloggInlaggID, adminStatus, namn);
                inlaggPaneler.add(nyttInlagg);
            }
            for (BloggInlaggsPanel inlagg : inlaggPaneler) {
                pnlInformellBlogg.add(inlagg);
            }
            revalidate();
        } catch (SQLException e) {
        }
    }//GEN-LAST:event_btnSorteraLikesActionPerformed

    private void btnUppdateraInformellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUppdateraInformellActionPerformed

        try {
            uppdateraInformellBlogg();
            uppdateraFormellBlogg();
            revalidate();
        } catch (SQLException e) {
        }
    }//GEN-LAST:event_btnUppdateraInformellActionPerformed

    private void btnVisaResultatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisaResultatActionPerformed
        txtVisaResultat.setText(null);
        getTodaysDate();

        try {
            ArrayList<ArrayList<String>> mote = SQL2.getPublicMeetings(db, dagensDatum);

            for (ArrayList<String> moten : mote) {
                String namn = moten.get(0);
                String beskrivning = moten.get(1);
                String fornamn = moten.get(2);
                String starttid = moten.get(3);
                String sluttid = moten.get(4);
                String datum = moten.get(5);
                String streck = moten.get(6);

                txtVisaResultat.append(namn + "\n\n");
                txtVisaResultat.append(beskrivning + "\n\n");
                txtVisaResultat.append(datum + " | " + starttid + " - " + sluttid + "\n" + "Skapad av: " + fornamn + "\n" + streck + "\n\n");
            }
        } catch (NoSuchAlgorithmException e) {
            System.out.print(e);
        } catch (SQLException e) {

        }
    }//GEN-LAST:event_btnVisaResultatActionPerformed

    private void getTodaysDate() {
        System.currentTimeMillis();
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
        Date date = new Date(System.currentTimeMillis());
        dagensDatum = formatter.format(date);

    }

    private void btnSkapaNyttMoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkapaNyttMoteActionPerformed
        new SkapaNyttMote(db, anvandarID).setVisible(true);
    }//GEN-LAST:event_btnSkapaNyttMoteActionPerformed

    private void btnMinaMotenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinaMotenActionPerformed
        // TODO add your handling code here:
        txtVisaResultat.setText(null);
        getTodaysDate();

        try {
            ArrayList<ArrayList<String>> mote = SQL2.getPrivateMeetings(db, dagensDatum);

            for (ArrayList<String> moten : mote) {
                String namn = moten.get(0);
                String beskrivning = moten.get(1);
                String fornamn = moten.get(2);
                String starttid = moten.get(3);
                String sluttid = moten.get(4);
                String datum = moten.get(5);
                String streck = moten.get(6);
                
                txtVisaResultat.append(namn + "\n\n");
                txtVisaResultat.append(beskrivning + "\n\n");
                txtVisaResultat.append(datum + " | " + starttid + " - " + sluttid + "\n" + "Skapad av: " + fornamn + "\n" + streck + "\n\n");
            }
        } catch (NoSuchAlgorithmException e) {
            System.out.print(e);
        } catch (SQLException e) {

        }
    }//GEN-LAST:event_btnMinaMotenActionPerformed

    private void jCalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jCalPropertyChange
        // TODO add your handling code here:
        txtVisaResultat.setText(null);

//      Hämtar ut all information från vårt kalenderobjekt.      
        Calendar calVart = jCal.getCalendar();
        Calendar cal = Calendar.getInstance();
        cal.add(Calendar.DATE, 0);
        Date date = calVart.getTime();
//      Ändrar  formatet på datumet.
        SimpleDateFormat format1 = new SimpleDateFormat("yyyy-MM-dd");
        String aktivtDatum = "";
        aktivtDatum = format1.format(date);

        try {
            ArrayList<ArrayList<String>> mote = SQL2.sqlKalender(db, aktivtDatum, anvandarID);

            for (ArrayList<String> moten : mote) {
                String namn = moten.get(0);
                String beskrivning = moten.get(1);
                String fornamn = moten.get(2);
                String starttid = moten.get(3);
                String sluttid = moten.get(4);
                String streck = moten.get(5);

                txtVisaResultat.append(namn + "\n\n");
                txtVisaResultat.append(beskrivning + "\n\n");
                txtVisaResultat.append(starttid + " - " + sluttid + "\n" + "Skapad av: " + fornamn + "\n" + streck + "\n\n");
                
            }
        } catch (NoSuchAlgorithmException e) {
            System.out.print(e);
        } catch (SQLException e) {

        }


    }//GEN-LAST:event_jCalPropertyChange

    private void btnUppdateraFormellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUppdateraFormellActionPerformed

        try {
            uppdateraFormellBlogg();
            uppdateraInformellBlogg();
            revalidate();
        } catch (SQLException e) {
        }
    }//GEN-LAST:event_btnUppdateraFormellActionPerformed

    private void btnUppdateraProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUppdateraProjektActionPerformed
       try {
            cmbProjektModel.removeAllElements();
            fyllPåCmbProjektgrupper();
        } catch (SQLException e) {
        }

    }//GEN-LAST:event_btnUppdateraProjektActionPerformed

    private void fyllPåCmbProjektgrupper() throws SQLException {

        ArrayList<ArrayList> projektArray = SQL.hamtaProjektGruppNamn(db, anvandarID);

        for (ArrayList<String> hamtadArray : projektArray) {
            if (hamtadArray != null) {
                for (String projektNamn : hamtadArray) {
                    //cmbProjektLista.addItem(projektNamn);

                    cmbProjektModel.addElement(projektNamn);
                }
            }
        }

        cmbProjektLista.setModel(cmbProjektModel);
    }

    public void uppdateraFormellBlogg() throws SQLException {
        pnlFormellBlogg.removeAll();

        ArrayList<ArrayList<String>> bloggInlagg = SQL.lasFormellaBlogginlagg(db);
        ArrayList<BloggInlaggsPanel> inlaggPaneler = new ArrayList<>();

        for (ArrayList<String> inlagg : bloggInlagg) {
            String rubrik = inlagg.get(0);
            String text = inlagg.get(1);
            String filURL = inlagg.get(2);
            String datum = inlagg.get(3);
            String skapatAv = inlagg.get(4);
            String bloggInlaggID = inlagg.get(5);
            String namn = inlagg.get(6);
            BloggInlaggsPanel nyttInlagg = new BloggInlaggsPanel(db, rubrik, text, skapatAv, datum, filURL, anvandarID, bloggInlaggID, adminStatus, namn);
            inlaggPaneler.add(nyttInlagg);
        }

        for (BloggInlaggsPanel inlagg : inlaggPaneler) {
            pnlFormellBlogg.add(inlagg);
        }
    }

    public void uppdateraInformellBlogg() throws SQLException {

        pnlInformellBlogg.removeAll();

        ArrayList<ArrayList<String>> bloggInlagg = SQL.lasInformellaBlogginlagg(db);
        ArrayList<BloggInlaggsPanel> inlaggPaneler = new ArrayList<>();

        for (ArrayList<String> inlagg : bloggInlagg) {
            String rubrik = inlagg.get(0);
            String text = inlagg.get(1);
            String filURL = inlagg.get(2);
            String datum = inlagg.get(3);
            String skapatAv = inlagg.get(4);
            String bloggInlaggID = inlagg.get(5);
            String namn = inlagg.get(6);
            BloggInlaggsPanel nyttInlagg = new BloggInlaggsPanel(db, rubrik, text, skapatAv, datum, filURL, anvandarID, bloggInlaggID, adminStatus, namn);
            inlaggPaneler.add(nyttInlagg);
        }
        for (BloggInlaggsPanel inlagg : inlaggPaneler) {
            pnlInformellBlogg.add(inlagg);
        }
    }

    public String visaFilTyp(String fileName) {

        String fileType = "Undetermined";
        final File file = new File(fileName);

        try {
            fileType = Files.probeContentType(file.toPath());

        } catch (IOException e) {
            System.out.println("kan inte hitta filtypen för: " + fileName + " på grund av " + e);
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Programmet stöder inte den typen av filer. Var god välj pdf, jpg eller png");
        }

        return fileType;
    }

    public boolean checkPdf(String fileName) {
        boolean filCheck = false;
        try {
            if (visaFilTyp(fileName).equals("application/pdf")) {
                filCheck = true;
            }
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Programmet stöder inte den typen av filer. Var god välj pdf, jpg eller png");
        }

        return filCheck;
    }

    public boolean checkPng(String fileName) {
        boolean filCheck = false;

        if (visaFilTyp(fileName).equals("image/png")) {
            filCheck = true;
        }

        return filCheck;
    }

    public boolean checkJpg(String fileName) {
        boolean filCheck = false;

        if (visaFilTyp(fileName).equals("image/jpeg")) {
            filCheck = true;
        }

        return filCheck;
    }

    public void sparaFil(File fil, String namn) {

        File temp = new File("src\\systemutvecklingsprojekt\\AppData\\" + namn);
        File destination = new File(temp.getAbsolutePath());
        filePath = temp.toString();
        fil.renameTo(destination);

    }

    private void tomFalt() {
        txtEpost.setText("");
        txtFornamn.setText("");
        txtEfternamn.setText("");

        txtTelefonnummer.setText("");
        rbtnAdmin.setSelected(false);
        txtBrodtext.setText("");
        txtSattRubrik.setText("");
        lblVisaFilnamn.setText("Filnamn");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollPane1;
    private javax.swing.JScrollPane ScrollPane3;
    private javax.swing.JButton btnLaggTillFil;
    private javax.swing.JButton btnMinaMoten;
    private javax.swing.JButton btnNyttProjektInlagg;
    private javax.swing.JButton btnPublicera;
    private javax.swing.JButton btnSkapaKonto;
    private javax.swing.JButton btnSkapaNyProjektgrupp;
    private javax.swing.JButton btnSkapaNyttMote;
    private javax.swing.JButton btnSorteraLikes;
    private javax.swing.JButton btnUppdateraFormell;
    private javax.swing.JButton btnUppdateraInformell;
    private javax.swing.JButton btnUppdateraProjekt;
    private javax.swing.JButton btnVisaResultat;
    private javax.swing.JComboBox<String> cmbInlaggsTyp;
    private javax.swing.JComboBox<String> cmbProjektLista;
    private javax.swing.JButton jButton9;
    private com.toedter.calendar.JCalendar jCal;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JLabel lblValjBlogg;
    private javax.swing.JLabel lblValjProjektgrupp;
    private javax.swing.JLabel lblVisaFilnamn;
    private javax.swing.JPanel pnlAdminRights;
    private javax.swing.JPanel pnlFormellBlogg;
    private javax.swing.JPanel pnlInformellBlogg;
    private javax.swing.JPanel pnlProjektInlagg;
    private javax.swing.JRadioButton rbtnAdmin;
    private javax.swing.JScrollPane scrlProjektGrupper;
    private javax.swing.JTabbedPane tabbedPaneBar;
    private javax.swing.JTextArea txtBrodtext;
    private javax.swing.JTextField txtEfternamn;
    private javax.swing.JTextField txtEpost;
    private javax.swing.JTextField txtFornamn;
    private javax.swing.JTextField txtSattRubrik;
    private javax.swing.JTextField txtTelefonnummer;
    private javax.swing.JTextArea txtVisaResultat;
    // End of variables declaration//GEN-END:variables
}
