/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package systemutvecklingsprojekt;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.nio.file.Files;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author ifkli
 */
public class ProjektInlagg extends javax.swing.JFrame {

    private Connection db;
    private String rubrik;
    private String text;
    private int skrivenAv;
    private String filURL;
    private int anvandarID;
    private int projektInlaggID;
    private String filNamn;
    private File fil;
    private String filePath;
    private int projektGruppID;

    /**
     * Creates new form ProjektInlagg
     */
    public ProjektInlagg(Connection db, String rubrik, String text, String skrivenAv, String filURL, int anvandarID, String projektInlaggID, int projektGruppID) {
        this.db = db;
        this.rubrik = rubrik;
        this.text = text;
        this.skrivenAv = Integer.parseInt(skrivenAv);
        this.filURL = filURL;
        this.anvandarID = anvandarID;
        this.projektInlaggID = Integer.parseInt(projektInlaggID);
        this.filNamn = "";
        this.projektGruppID = projektGruppID;

        initComponents();

        try {

            String projektRubrik = SQL.getProjektNamn(db, projektGruppID);
            lblProjektRubrik.setText(projektRubrik);
        } catch (NoSuchAlgorithmException e) {
        } catch (SQLException e) {
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtRubrik = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtBrodtext = new javax.swing.JTextArea();
        btnPublicera = new javax.swing.JButton();
        lblRubrik = new javax.swing.JLabel();
        lblBrodtext = new javax.swing.JLabel();
        lblProjektRubrik = new javax.swing.JLabel();
        btnLaggTillFil = new javax.swing.JButton();
        lblVisaFilnamn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtBrodtext.setColumns(20);
        txtBrodtext.setRows(5);
        jScrollPane1.setViewportView(txtBrodtext);

        btnPublicera.setText("Publicera");
        btnPublicera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPubliceraActionPerformed(evt);
            }
        });

        lblRubrik.setText("Rubrik");

        lblBrodtext.setText("Brödtext");

        lblProjektRubrik.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblProjektRubrik.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProjektRubrik.setText("Projektnamn");

        btnLaggTillFil.setText("Lägg till fil");
        btnLaggTillFil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaggTillFilActionPerformed(evt);
            }
        });

        lblVisaFilnamn.setText("Filnamn");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRubrik)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnLaggTillFil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblVisaFilnamn, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPublicera))
                    .addComponent(lblRubrik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblBrodtext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblProjektRubrik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblProjektRubrik)
                .addGap(18, 18, 18)
                .addComponent(lblRubrik)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblBrodtext)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPublicera)
                    .addComponent(btnLaggTillFil)
                    .addComponent(lblVisaFilnamn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPubliceraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPubliceraActionPerformed
        String rubrik = txtRubrik.getText();
        String text = txtBrodtext.getText();
        int skrivenAv = anvandarID;

        try {

            if (Validering.textIsEmpty(txtRubrik)) {
                JOptionPane.showMessageDialog(null, "Vänligen fyll i rubrik");
            } else if (Validering.textAreaIsEmpty(txtBrodtext)) {
                JOptionPane.showMessageDialog(null, "Vänligen fyll i brödtext");
            } else {

                if (filNamn.equals("")) {
                    filePath = "";
                } else {
                    sparaFil(fil, filNamn);
                }

                SQL.laggaTillProjektInlagg(db, rubrik, text, filePath, skrivenAv, projektGruppID);
                JOptionPane.showMessageDialog(null, "Inlägg publicerat!");
                dispose();
            }
        } catch (SQLException e) {

        } catch (NoSuchAlgorithmException er) {
        }

    }//GEN-LAST:event_btnPubliceraActionPerformed

    private void btnLaggTillFilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaggTillFilActionPerformed

        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        fil = chooser.getSelectedFile();

        String filName = String.valueOf(fil);

        if (!filName.equals("null")) {
            filNamn = chooser.getName(fil);

            if (checkPdf(filNamn)) {
            int input = JOptionPane.showConfirmDialog(null, "Filen kommer försvinna från din dator. "
                    + "Om du vill spara filen på datorn, skapa en kopia innan du publicerar.", null,
                    JOptionPane.OK_CANCEL_OPTION);

            if (input == 0) {
                lblVisaFilnamn.setText(filNamn);
                //System.out.println("1. " + filNamn);
            } else if(input == 2){
                lblVisaFilnamn.setText("Filnamn");
                //System.out.println("2. " + filNamn);
                filNamn = "";
                //System.out.println("2.1 " + filNamn);
            }
                
            } else {
                JOptionPane.showMessageDialog(null, "Du måste välja en pdf fil");
            }

        }

    }//GEN-LAST:event_btnLaggTillFilActionPerformed

    public boolean checkPdf(String fileName) {
        boolean filCheck = false;
        try {
            if (visaFilTyp(fileName).equals("application/pdf")) {
                filCheck = true;
            }
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Programmet stöder inte den typen av filer. Var god välj pdf, jpg eller png");
        }

        return filCheck;
    }

    public void sparaFil(File fil, String namn) {
        File temp = new File("src/systemutvecklingsprojekt/AppData/" + namn);
        
        filePath = "src/systemutvecklingsprojekt/AppData/" + namn;
        
        File destination = new File(temp.getAbsolutePath());    
        fil.renameTo(destination);
    }

    public String visaFilTyp(String fileName) {

        String fileType = "Undetermined";
        final File file = new File(fileName);

        try {
            fileType = Files.probeContentType(file.toPath());
            System.out.println(fileType);

        } catch (IOException e) {
            System.out.println("kan inte hitta filtypen för: " + fileName + " på grund av " + e);
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Programmet stöder inte den typen av filer. Var god välj pdf, jpg eller png");
        }

        return fileType;
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ProjektInlagg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ProjektInlagg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ProjektInlagg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ProjektInlagg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ProjektInlagg().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLaggTillFil;
    private javax.swing.JButton btnPublicera;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBrodtext;
    private javax.swing.JLabel lblProjektRubrik;
    private javax.swing.JLabel lblRubrik;
    private javax.swing.JLabel lblVisaFilnamn;
    private javax.swing.JTextArea txtBrodtext;
    private javax.swing.JTextField txtRubrik;
    // End of variables declaration//GEN-END:variables
}
