/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package systemutvecklingsprojekt;

import javax.swing.JFrame;
import javax.swing.JPanel;
import java.awt.BorderLayout;
import java.awt.Desktop;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.*;
import java.io.File;
import java.io.IOException;

/**
 *
 * @author ifkli
 */
public class ProjektInlaggsPanel extends javax.swing.JPanel {

    private Connection db;
    private String rubrik;
    private String text;
    private int skapatAvID;
    private String namn;
    private String filURL;
    private int anvandarID;
    private int projektInlaggID;

    /**
     * Creates new form BloggInlaggsPanel
     */
    public ProjektInlaggsPanel(Connection db, String rubrik, String text, String skapatAvID, String filURL, int anvandarID, String namn, String projektInlaggID) {
        this.db = db;
        this.rubrik = rubrik;
        this.text = text;
        this.skapatAvID = Integer.parseInt(skapatAvID);
        this.filURL = filURL;
        this.anvandarID = anvandarID;
        this.namn = namn;
        this.projektInlaggID = Integer.parseInt(projektInlaggID);

        initComponents();

        lblRubrik.setText(rubrik);
        txtBloggtext.setText(text);
        lblForfattare.setText(namn);
        btnTaBort.setVisible(false);

        if (SQL.getFilURL(db, Integer.parseInt(projektInlaggID)).equals("")) {
            btnPDFfil.setVisible(false);
        }

        if (anvandarID == this.skapatAvID) {
            btnTaBort.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtBloggtext = new javax.swing.JTextArea();
        btnTaBort = new javax.swing.JButton();
        lblRubrik = new javax.swing.JLabel();
        lblForfattare = new javax.swing.JLabel();
        btnPDFfil = new javax.swing.JButton();

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtBloggtext.setEditable(false);
        txtBloggtext.setColumns(20);
        txtBloggtext.setLineWrap(true);
        txtBloggtext.setRows(5);
        jScrollPane1.setViewportView(txtBloggtext);

        btnTaBort.setText("Ta bort");
        btnTaBort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaBortActionPerformed(evt);
            }
        });

        lblRubrik.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblRubrik.setText("Rubrik visas här");

        lblForfattare.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblForfattare.setText("Admin Adminsson");

        btnPDFfil.setText("Öppna PDF-fil");
        btnPDFfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPDFfilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 123, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnTaBort)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnPDFfil))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblForfattare, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRubrik)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblForfattare, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTaBort)
                    .addComponent(btnPDFfil))
                .addContainerGap(25, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTaBortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaBortActionPerformed
        try {
            int input = JOptionPane.showConfirmDialog(null, "Vill du verkligen radera detta inlägg?", null,
                    JOptionPane.OK_CANCEL_OPTION);

            if (input == 0) {
                SQL.raderaProjektInlagg(db, projektInlaggID);
            }
        } catch (NoSuchAlgorithmException e) {

        } catch (SQLException i) {

        }
    }//GEN-LAST:event_btnTaBortActionPerformed

    private void btnPDFfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPDFfilActionPerformed

        if (Desktop.isDesktopSupported()) {
            try {
                if (!SQL.getFilURL(db, projektInlaggID).equals("")) {
                    File myFile = new File(SQL.getFilURL(db, projektInlaggID));
                    System.out.println(projektInlaggID);
                    System.out.println(SQL.getFilURL(db, projektInlaggID));
                    Desktop.getDesktop().open(myFile);
                } else {
                    btnPDFfil.setText("Ingen fil");
                    System.out.println("Finns ingen fil");
                }
            } catch (IOException ex) {
                // no application registered for PDFs
            }
        }

    }//GEN-LAST:event_btnPDFfilActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPDFfil;
    private javax.swing.JButton btnTaBort;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblForfattare;
    private javax.swing.JLabel lblRubrik;
    private javax.swing.JTextArea txtBloggtext;
    // End of variables declaration//GEN-END:variables
}
