/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package systemutvecklingsprojekt;


import java.sql.Array;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import javax.swing.text.DateFormatter;
/**
 *
 * @author vince
 */
public class SkapaNyttMote extends javax.swing.JFrame {

    /**
     * Creates new form SkapaNyttProjekt
     */
        private static Connection db;
        private DefaultListModel valdMedlemListModel;
        private DefaultListModel valjMedlemListModell;
        private int anvandarID;
    
    
    public SkapaNyttMote(Connection db, int anvandarID) {
        this.db = db;
        this.anvandarID = anvandarID;
        valdMedlemListModel = new DefaultListModel();
        valjMedlemListModell = new DefaultListModel();
        initComponents();
        lblValtdatumResultat.setVisible(false);
        lblValtDatum.setVisible(false);
        txtUpptagnaAnv.setVisible(false);
        lblUpptagnaAnv.setVisible(false);
        jScrollPane4.setVisible(false);
        formeterarTid (jSpinnerStartTid);
        formeterarTid (jSpinnerslutTid);
        revalidate();
        this.setLocationRelativeTo(null); //SÄTTER FÖNSTRET I MITTEN AV SKÄRMEN NÄR DEN SKAPAS
       
        try{
        listaAllaAnvandare();
            
        }
            catch(SQLException e){
                
            }
        listValjMedlemmar.setSelectedIndex(0);
    }
    
    private void listaAllaAnvandare() throws SQLException{
        
        ArrayList<ArrayList<String>> resultatLista = SQL.getAnvandareItemList(db);
        
            for(ArrayList<String> anvandare : resultatLista){
                String anvandarInfo = anvandare.get(2) + " " + anvandare.get(3) + " "  + anvandare.get(1);
                
                valjMedlemListModell.addElement(anvandarInfo);
                listValjMedlemmar.setModel(valjMedlemListModell);
                System.out.println(anvandarInfo);
            }
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabelmotesrubrik = new javax.swing.JLabel();
        txtProjektRubrik = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaBeskrivning = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        btnSkapaMote = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listValjMedlemmar = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        listValdaMedlemmar = new javax.swing.JList<>();
        btnTaBortMedl = new javax.swing.JButton();
        btnLaggTillMedl = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSpinnerStartTid = new javax.swing.JSpinner();
        jSpinnerslutTid = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jCal = new com.toedter.calendar.JCalendar();
        lblValtDatum = new javax.swing.JLabel();
        lblValtdatumResultat = new javax.swing.JLabel();
        jChkPubliktMote = new javax.swing.JCheckBox();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtUpptagnaAnv = new javax.swing.JTextArea();
        lblUpptagnaAnv = new javax.swing.JLabel();
        lblMaxTecken = new javax.swing.JLabel();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelmotesrubrik.setText("Mötesnamn:");

        txtAreaBeskrivning.setColumns(20);
        txtAreaBeskrivning.setLineWrap(true);
        txtAreaBeskrivning.setRows(5);
        txtAreaBeskrivning.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAreaBeskrivningKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(txtAreaBeskrivning);

        jLabel3.setText("Beskrivning av mötet:");

        btnSkapaMote.setText("Skicka inbjudan");
        btnSkapaMote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSkapaMoteActionPerformed(evt);
            }
        });

        listValjMedlemmar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setViewportView(listValjMedlemmar);

        jScrollPane3.setViewportView(listValdaMedlemmar);

        btnTaBortMedl.setText("Ta bort");
        btnTaBortMedl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaBortMedlActionPerformed(evt);
            }
        });

        btnLaggTillMedl.setText("Lägg till");
        btnLaggTillMedl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaggTillMedlActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/systemutvecklingsprojekt/MOTENBANNER.png"))); // NOI18N

        jLabel4.setText("Välj använddare");

        jLabel5.setText("Valda användare");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/systemutvecklingsprojekt/INFORTELJBREOALJBF90.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/systemutvecklingsprojekt/VertikalHöger.png"))); // NOI18N

        jSpinnerStartTid.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(1587548549512L), null, java.util.Calendar.MINUTE));

        jSpinnerslutTid.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(1587548601505L), null, java.util.Calendar.MINUTE));

        jLabel8.setText("Starttid:");

        jLabel9.setText("Sluttid:");

        jCal.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jCalPropertyChange(evt);
            }
        });

        lblValtDatum.setText("Valt datum:");

        jChkPubliktMote.setText("Publikt möte");
        jChkPubliktMote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkPubliktMoteActionPerformed(evt);
            }
        });

        txtUpptagnaAnv.setColumns(20);
        txtUpptagnaAnv.setLineWrap(true);
        txtUpptagnaAnv.setRows(5);
        jScrollPane4.setViewportView(txtUpptagnaAnv);

        lblUpptagnaAnv.setText("Ej tillgängliga användare");

        lblMaxTecken.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblMaxTecken.setText("Max 200 tecken (200/200)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLaggTillMedl)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jChkPubliktMote, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblMaxTecken, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabelmotesrubrik, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtProjektRubrik, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTaBortMedl)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(145, 145, 145)
                                    .addComponent(btnSkapaMote)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jSpinnerStartTid, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel9)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jSpinnerslutTid, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblValtDatum)
                                            .addGap(18, 18, 18)
                                            .addComponent(lblValtdatumResultat, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(116, 116, 116)))))
                            .addComponent(jCal, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblUpptagnaAnv)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(20, 20, 20)))
                .addComponent(jLabel7))
            .addComponent(jLabel1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabelmotesrubrik)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(txtProjektRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(34, 34, 34)
                                        .addComponent(jChkPubliktMote)
                                        .addGap(7, 7, 7)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(179, 179, 179))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnLaggTillMedl)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jCal, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblValtDatum)
                                            .addComponent(lblValtdatumResultat))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(jSpinnerStartTid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)
                                    .addComponent(jSpinnerslutTid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSkapaMote))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblMaxTecken)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTaBortMedl)
                                .addGap(43, 43, 43)
                                .addComponent(lblUpptagnaAnv)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 748, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLaggTillMedlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaggTillMedlActionPerformed
        laggTillMedlemmar();
        
        try{
            kollaLedigDatum();
        }
        catch(SQLException e){
        }
        
        
    }//GEN-LAST:event_btnLaggTillMedlActionPerformed

    private void btnTaBortMedlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaBortMedlActionPerformed
            try{
                 listValdaMedlemmar.getSelectedValue();
                 valdMedlemListModel.removeElementAt(listValdaMedlemmar.getSelectedIndex());
            }
            catch(Exception e){  
            }
            
            try{
            kollaLedigDatum();
           }
            catch(SQLException e){
            }
            
    }//GEN-LAST:event_btnTaBortMedlActionPerformed

    private void btnSkapaMoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkapaMoteActionPerformed
     
        if(Validering.textIsEmpty(txtProjektRubrik) || Validering.textAreaIsEmpty(txtAreaBeskrivning) || listValdaMedlemmar.getModel().getSize() == 0){
            
                JOptionPane.showMessageDialog(null, "Vänligen fyll i Rubrik, Beskrivning och lägg till medlemmar!");
        }
        else if(Validering.textAreaExceedsLimit(txtAreaBeskrivning, 200)){
                JOptionPane.showMessageDialog(null, "Mötesbeskrivning för lång! Max 200 tecken.");        
        }
        else{
                ArrayList<String> medlemsEpostLista = new ArrayList<>();
           
             for(int i = 0; i<listValdaMedlemmar.getModel().getSize(); i++){
                String[] enMedlem = listValdaMedlemmar.getModel().getElementAt(i).split(" ");
                    medlemsEpostLista.add(enMedlem[2]);
                
                 System.out.println(medlemsEpostLista);
            } 
            try{
                ArrayList<Integer> enIDLista = SQL.epostTillAnvandarID(db, medlemsEpostLista);
                
                 SimpleDateFormat tidformaterare = new SimpleDateFormat("HH:mm");
                 String motesStartTid = tidformaterare.format(jSpinnerStartTid.getValue());
                 String motesSlutTid = tidformaterare.format(jSpinnerslutTid.getValue());
                 
                 SimpleDateFormat datumformaterare = new SimpleDateFormat("yyyy-MM-dd");
                 String datum = datumformaterare.format(jCal.getDate());
                 String motesNamn = txtProjektRubrik.getText();
                 
                 if(jChkPubliktMote.isSelected()){
                      motesNamn = "PUBLIKT MÖTE: \n" + motesNamn;
                      System.out.println(motesNamn);
                 }
                 SQL.skapaNyttMote(db, enIDLista, motesNamn, txtAreaBeskrivning.getText(), datum, motesStartTid, motesSlutTid, anvandarID);
                 
                }
                catch(SQLException e){
                }

                     JOptionPane.showMessageDialog(null, "Inbjudningar till mötet: '" + txtProjektRubrik.getText() + "' är nu skickade.");
                     dispose();
                    }
    }//GEN-LAST:event_btnSkapaMoteActionPerformed

    private void jCalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jCalPropertyChange
        
        Calendar calVart = jCal.getCalendar();
        Calendar cal = Calendar.getInstance();
        cal.add(Calendar.DATE, 0);
        Date date = calVart.getTime();
        //Ändrar  formatet på datumet.
        SimpleDateFormat format1 = new SimpleDateFormat("yyyy-MM-dd");
        String aktivtDatum = null;
        aktivtDatum = format1.format(date);
        
        System.out.println(aktivtDatum);
        
        lblValtdatumResultat.setVisible(true);
        lblValtDatum.setVisible(true);
        lblValtdatumResultat.setText(aktivtDatum);
        try{
            kollaLedigDatum();
        }
        catch(SQLException e){
        }
    }//GEN-LAST:event_jCalPropertyChange
    
    private void kollaLedigDatum() throws SQLException{ //Kalla på SQL-klass för att se om användare för valt datum är ledig
        ArrayList<String> medlemsEpostLista = new ArrayList<>();
           
        for(int i = 0; i<listValdaMedlemmar.getModel().getSize(); i++){
             String[] enMedlem = listValdaMedlemmar.getModel().getElementAt(i).split(" ");
             medlemsEpostLista.add(enMedlem[2]);
                
             System.out.println(medlemsEpostLista);
        } 
            Calendar calVart = jCal.getCalendar();
            Calendar cal = Calendar.getInstance();
            cal.add(Calendar.DATE, 0);
            Date date = calVart.getTime();
            //Ändrar  formatet på datumet.
            SimpleDateFormat format1 = new SimpleDateFormat("yyyy-MM-dd");
            String aktivtDatum = null;
            aktivtDatum = format1.format(date);
            
            ArrayList<String> upptagnaAnv = SQL.kollaOmLedigtDatum(db, aktivtDatum, SQL.epostTillAnvandarID(db, medlemsEpostLista));
                if(upptagnaAnv.isEmpty()){
                    jScrollPane4.setVisible(false);
                    txtUpptagnaAnv.setVisible(false);
                    lblUpptagnaAnv.setVisible(true);
                    lblUpptagnaAnv.setText("Datumet är ledigt");
                }
                else{
                    jScrollPane4.setVisible(true);
                    txtUpptagnaAnv.setVisible(true);
                    lblUpptagnaAnv.setVisible(true);
                    lblUpptagnaAnv.setText("Upptagna användare");
                    
                    String textAttPrinta = "";
                    for(String uppTagen : upptagnaAnv){
                    textAttPrinta += uppTagen;    
                    }
                      txtUpptagnaAnv.setText(textAttPrinta);
                }    
        //Printa i textArea
    }
    
    
    
    private void jChkPubliktMoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkPubliktMoteActionPerformed
        // TODO add your handling code here:
        if(jChkPubliktMote.isSelected()){
            listValdaMedlemmar.setModel(valjMedlemListModell);

        }
        else{
            listValdaMedlemmar.setModel(valdMedlemListModel);
        }
        
    }//GEN-LAST:event_jChkPubliktMoteActionPerformed

    private void txtAreaBeskrivningKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAreaBeskrivningKeyReleased
        String texten = txtAreaBeskrivning.getText();
        int stringLangd = texten.length();
        lblMaxTecken.setText("Max 200 tecken (" + (200 - stringLangd) + "/200)");
        revalidate();     }//GEN-LAST:event_txtAreaBeskrivningKeyReleased

    public static void formeterarTid (JSpinner spinner){
    
    Calendar calendar = Calendar.getInstance();
    calendar.set(Calendar.HOUR_OF_DAY, 24);
    calendar.set(Calendar.MINUTE, 0);
    
    SpinnerDateModel model = new SpinnerDateModel();
    model.setValue(calendar.getTime());

    spinner.setModel(model);
    JSpinner.DateEditor editor = new JSpinner.DateEditor(spinner, "HH:mm");
    DateFormatter formatter = (DateFormatter)editor.getTextField().getFormatter();
    formatter.setAllowsInvalid(false); // this makes what you want
    formatter.setOverwriteMode(true);
    
    spinner.setEditor(editor);
    }
    
    
    private void laggTillMedlemmar(){
        boolean finnsRedan = false;
        String valdMedlem = listValjMedlemmar.getSelectedValue();
        
        for(int i = 0; i<listValdaMedlemmar.getModel().getSize(); i++){
           String enMedlem = listValdaMedlemmar.getModel().getElementAt(i);
           
                if(valdMedlem.equals(enMedlem)){
                    finnsRedan = true;
                }
                   
        }  
        
        if(finnsRedan == false){
            System.out.println(valdMedlem);
        
            valdMedlemListModel.addElement(valdMedlem);
            listValdaMedlemmar.setModel(valdMedlemListModel);
        }
        else{
            JOptionPane.showMessageDialog(null, "Personen du valt är redan tillagd!");
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(SkapaNyttProjekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(SkapaNyttProjekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(SkapaNyttProjekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(SkapaNyttProjekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new SkapaNyttProjekt(db).setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLaggTillMedl;
    private javax.swing.JButton btnSkapaMote;
    private javax.swing.JButton btnTaBortMedl;
    private com.toedter.calendar.JCalendar jCal;
    private javax.swing.JCheckBox jChkPubliktMote;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelmotesrubrik;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSpinner jSpinnerStartTid;
    private javax.swing.JSpinner jSpinnerslutTid;
    private javax.swing.JLabel lblMaxTecken;
    private javax.swing.JLabel lblUpptagnaAnv;
    private javax.swing.JLabel lblValtDatum;
    private javax.swing.JLabel lblValtdatumResultat;
    private javax.swing.JList<String> listValdaMedlemmar;
    private javax.swing.JList<String> listValjMedlemmar;
    private javax.swing.JTextArea txtAreaBeskrivning;
    private javax.swing.JTextField txtProjektRubrik;
    private javax.swing.JTextArea txtUpptagnaAnv;
    // End of variables declaration//GEN-END:variables
}
